FROM ubuntu:wily
MAINTAINER Oleksii Aliakin <alex@nls.la>
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get upgrade -y       && \
    apt-get install --no-install-recommends -y    \
        git gcc g++ qt5-default qtdeclarative5-dev libqt5svg5-dev qbs

# build fgap
CMD qbs setup-toolchains --detect        && \
    qbs setup-qt --detect                && \
    qbs setup-qt $(which qmake) qt       && \
    qbs config defaultProfile qt         && \
    cd /fgap/src                         && \
    qbs --command-echo-mode command-line \
        -d /tmp/fgap_build/              \
        --clean-install-root qbs.installRoot:/result/install
